unstable_features = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
merge_derives = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
newline_style = "Native"