INPUT      = _{ !NEWLINE ~ ANY }
COMMENT    = _{ (("#" ~ !"##") | "//") ~ INPUT* ~ NEWLINE }
SP         = _{ " " }
WHITESPACE = _{ SP }
ALPHA      = _{ 'a'..'z' | 'A'..'Z' }
DIGIT      = _{ '0'..'9' }
IDENT      = _{ (ALPHA | "_") ~ (ALPHA | DIGIT | "_" | "-")* }
EMPTY_LINE = _{ NEWLINE ~ !INPUT }
INDENT     = _{ "\t" | "    " | "   " | "  " | " " }
INDENTED_NEWLINE  = @{ NEWLINE ~ INDENT }

/// Request separator
request_separator = { "###" ~ INPUT* ~ &NEWLINE }

/// Request Line
// Like target, method, authority, etc.
request_line = _{ SP* ~ method? ~ request_target ~ (SP+ ~ http_version)? ~ SP* }
http_version = ${ "HTTP/" ~ DIGIT+ ~ "." ~ DIGIT+ }
method_name  = _{ "GET" | "HEAD" | "POST" | "PUT" | "DELETE" | "CONNECT" | "PATCH" | "OPTIONS" | "TRACE" }
method       = @{ method_name ~ SP+ }

/// Request target
request_target = @{ absolute_form | origin_form | asterisk_form }
origin_form    =  { absolute_path ~ ("?" ~ query)? ~ ("#" ~ fragment)? }
absolute_form  =  { (scheme ~ "://")? ~ hier_part ~ ("?" ~ query)? ~ ("#" ~ fragment)? }
hier_part      =  { authority ~ absolute_path? }
asterisk_form  =  { "*" }
scheme         =  { "https" | "http" }

// authority
authority             =  { host ~ (":" ~ port)? }
port                  =  { DIGIT+ }
host                  =  { ipv6_address | ipv4_or_reg_name }
ipv6_input_char       = _{ !("/" | "]") ~ INPUT }
ipv6_address          =  { "[" ~ ipv6_input_char+ ~ "]" }
ipv4_or_reg_name_char = _{ !("/" | ":" | "?" | "#") ~ INPUT }
ipv4_or_reg_name      =  { ipv4_or_reg_name_char+ }

// resource
absolute_path     =  { (path_separator ~ path_segment)+ | "/" }
path_separator    =  { "/" | INDENTED_NEWLINE }
path_segment_char = _{ !("/" | "?" | "#") ~ INPUT }
path_segment      =  { path_segment_char* }

// query and fragment
query_char            = _{ !"#" ~ INPUT }
query_with_newline    = _{ INDENTED_NEWLINE ~ query }
query                 = @{ query_char* ~ query_with_newline? }
fragment_char         = _{ !"?" ~ INPUT }
fragment_with_newline = _{ INDENTED_NEWLINE ~ fragment }
fragment              = @{ fragment_char* ~ fragment_with_newline? }

/// Headers
headers      = _{ (header_field ~ NEWLINE)* }
header_field = { header_name ~ ":" ~ SP* ~ header_value }
header_name  = ${ IDENT }
header_value = { INPUT+ }

/// Message Body
message_body   =  { messages | multipart_form_data }
messages       = @{ message_line ~ (NEWLINE ~ message_line)* }
message_line   =  { (!("<" | "<> " | "###" | "> {%") ~ INPUT*) | input_file_ref }
input_file_ref =  { "< " ~ file_path }
file_path      =  { INPUT+ ~ NEWLINE }

// multipart-form-data
multipart_form_data = { multipart_field ~ multipart_form_data? ~ boundary }
multipart_field     = { boundary ~ (header_field ~ NEWLINE)* ~ NEWLINE ~ messages? }
boundary            = { "--" ~ INPUT ~ NEWLINE }

/// Response Handler
response_handler        =  { response_handler_script | response_handler_ref }
response_handler_script = _{ "> {%" ~ handler_script ~ "%}" }
response_handler_ref    =  { "> " ~ file_path }
handler_script          =  { (!"%}" ~ ANY)* }

/// Pre request script
request_handler        =  { request_handler_script | request_handler_ref }
request_handler_script = _{ "< {%" ~ pre_handler_script ~ "%}" }
request_handler_ref    =  { "< " ~ file_path }
pre_handler_script     =  { (!"%}" ~ ANY)* }

/// Request variables block
// e.g. @variable=value
request_variable_name         = { IDENT }
request_variable_value        = { (INPUT)* }
request_variable_declaration  = { "@" ~ request_variable_name ~ SP* ~ "=" ~ SP* ~ request_variable_value }
request_variable_declarations = _{ (request_variable_declaration ~ NEWLINE*)+ }

/// Response Reference
response_reference = @{ "<> " ~ file_path }

/// Full request
request                 = _{ request_line ~ NEWLINE ~ headers ~ (NEWLINE ~ message_body)? }
request_script_with_sep = _{ NEWLINE* ~ request_separator ~ request_script }
request_script          =  {
    NEWLINE* ~ request_variable_declarations? ~ 
    NEWLINE* ~ request_handler? ~ 
    NEWLINE* ~ request ~ 
    NEWLINE* ~ response_handler? ~ 
    NEWLINE* ~ response_reference? ~ 
    NEWLINE*
}

file = { 
    SOI ~ NEWLINE* ~ 
    request_separator? ~ request_script ~ 
    request_script_with_sep* ~ 
    request_separator? ~ NEWLINE* ~
    EOI 
}
