name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install ${{ matrix.target }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install gcc-aarch64-linux-gnu
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -yq gcc-aarch64-linux-gnu

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: /usr/bin/aarch64-linux-gnu-gcc
        run: cargo build --release --bin dothttp --locked --target ${{ matrix.target }}

      - name: Pack artifacts [Linux & macOS]
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        env:
          TARGET_NAME: dothttp-${{ matrix.target }}
        run: |
          mkdir $TARGET_NAME
          cp target/${{ matrix.target }}/release/dothttp $TARGET_NAME
          cp README.md LICENSE $TARGET_NAME
          zip -r $TARGET_NAME.zip $TARGET_NAME

      - name: Pack artifacts [Windows]
        if: matrix.os == 'windows-latest'
        env:
          TARGET_NAME: dothttp-${{ matrix.target }}
        run: |
          New-Item -ItemType Directory -Path ${env:TARGET_NAME}
          Copy-Item -Path "target\${{ matrix.target }}\release\dothttp.exe" -Destination ${env:TARGET_NAME}
          Copy-Item -Path "README.md", "LICENSE" -Destination ${env:TARGET_NAME}
          Compress-Archive -Path ${env:TARGET_NAME} -DestinationPath "${env:TARGET_NAME}.zip"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: dothttp-${{ matrix.target }}.zip
          generate_release_notes: true
